server:
  port: 8888


# Init Chaos Monkey for Spring Boot by profile
spring:
  profiles:
    active: native,chaos-monkey
  application:
    name: config-center
  cloud:
    kubernetes:
      enabled: false
    config:
      server:
        native:
          search-locations: classpath:/shared


# Configure Chaos Monkey - enabled = false
chaos:
  monkey:
#    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      latency-active: true

# Spring Boot Actuator Endpoint Chaos Monkey for Spring Boot
management:
  endpoint:
    chaosmonkey:
      enabled: true
    restart:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/