 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: spring-cloud-kubernetes-ingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: wwww.spring-cloud-kubernetes-ingress.com
     http:
       paths:
       - path: /
         backend:
           serviceName: spring-cloud-gateway
           servicePort: 8887