---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.dekorate.io/commit-id: "46331ca99ad074f2fd1fb9420da143e48240f05b"
  labels:
    app.kubernetes.io/name: "spring-boot-v1-kubernetes-demo"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
  name: "spring-boot-v1-kubernetes-demo"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.dekorate.io/commit-id: "46331ca99ad074f2fd1fb9420da143e48240f05b"
  labels:
    app.kubernetes.io/name: "spring-boot-v1-kubernetes-demo"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
  name: "spring-boot-v1-kubernetes-demo"
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: "spring-boot-v1-kubernetes-demo"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
  loadBalancerIP: 52.130.150.228
  type: "LoadBalancer"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  annotations:
    app.dekorate.io/vcs-url: "https://github.com/huqianghui/dataOps.git"
    app.dekorate.io/commit-id: "46331ca99ad074f2fd1fb9420da143e48240f05b"
  labels:
    app.kubernetes.io/name: "spring-boot-v1-kubernetes-demo"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
  name: "spring-boot-v1-kubernetes-demo:view"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "view"
subjects:
  - kind: "ServiceAccount"
    name: "spring-boot-v1-kubernetes-demo"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.dekorate.io/vcs-url: "https://github.com/huqianghui/dataOps.git"
    app.dekorate.io/commit-id: "46331ca99ad074f2fd1fb9420da143e48240f05b"
  labels:
    app.kubernetes.io/name: "spring-boot-v1-kubernetes-demo"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
  name: "spring-boot-v1-kubernetes-demo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "spring-boot-v1-kubernetes-demo"
      app.kubernetes.io/version: "1.0-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: "https://github.com/huqianghui/dataOps.git"
        app.dekorate.io/commit-id: "46331ca99ad074f2fd1fb9420da143e48240f05b"
      labels:
        app.kubernetes.io/name: "spring-boot-v1-kubernetes-demo"
        app.kubernetes.io/version: "1.0-SNAPSHOT"
    spec:
      containers:
        - env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
          image: "springcloud2k8s3acr.azurecr.cn/spring-boot-v1-kubernetes-demo:1.2.0.12-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/health"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: "spring-boot-v1-kubernetes-demo"
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/info"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: "spring-boot-v1-kubernetes-demo"