spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
    config:
      uri: http://spring-config-server:8888
eureka:
  client:
    enabled: false

server:
  port: 9003

dekorate:
  kubernetes:
    serviceType: "NodePort"
