logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: troubleshooting
  cloud:
    kubernetes:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: webdemo-service
          uri: lb://webdemo
          predicates:
            - Path=/webdemo/hello/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/oauth/**
        - id: grahql-service-ws
          uri: lb:ws://grahql-service
          predicates:
            - Path=/subscriptions
        - id: grahql-service
          uri: lb://grahql-service
          predicates:
            - Path=/graphql
  security:
    oauth2:
      client:
        registration:
          gateway:
            client-id: gateway
            client-secret: gateway
            authorization-grant-type: client_credentials
            redirect-uri: http://localhost:8887/index.html
            scope: server
        provider:
          gateway:
            authorization-uri: http://auth-service:6000/oauth/authorize
            token-uri: http://auth-service:6000/oauth/token
            user-info-uri: http://auth-service:6000/userinfo
            user-name-attribute: user_name
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: info,health,mappings,hystrix.stream