---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.dekorate.io/commit-id: "f5c5669722ffb336db56957fd3a9a7e6fbc190df"
    app.dekorate.io/vcs-url: "https://github.com/huqianghui/kubernetes.git"
  labels:
    app.kubernetes.io/name: "spring-config-server"
    app.kubernetes.io/version: "1.0.3-SNAPSHOT"
  name: "spring-config-server"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.dekorate.io/commit-id: "f5c5669722ffb336db56957fd3a9a7e6fbc190df"
    app.dekorate.io/vcs-url: "https://github.com/huqianghui/kubernetes.git"
  labels:
    app.kubernetes.io/name: "spring-config-server"
    app.kubernetes.io/version: "1.0.3-SNAPSHOT"
  name: "spring-config-server"
spec:
  ports:
  - name: "http"
    port: 8888
    targetPort: 8888
  selector:
    app.kubernetes.io/name: "spring-config-server"
    app.kubernetes.io/version: "1.0.3-SNAPSHOT"
  type: "NodePort"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  annotations:
    app.dekorate.io/commit-id: "f5c5669722ffb336db56957fd3a9a7e6fbc190df"
    app.dekorate.io/vcs-url: "https://github.com/huqianghui/kubernetes.git"
  labels:
    app.kubernetes.io/name: "spring-config-server"
    app.kubernetes.io/version: "1.0.3-SNAPSHOT"
  name: "spring-config-server:view"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "view"
subjects:
- kind: "ServiceAccount"
  name: "spring-config-server"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.dekorate.io/commit-id: "f5c5669722ffb336db56957fd3a9a7e6fbc190df"
    app.dekorate.io/vcs-url: "https://github.com/huqianghui/kubernetes.git"
  labels:
    app.kubernetes.io/name: "spring-config-server"
    app.kubernetes.io/version: "1.0.3-SNAPSHOT"
  name: "spring-config-server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "spring-config-server"
      app.kubernetes.io/version: "1.0.3-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.dekorate.io/commit-id: "f5c5669722ffb336db56957fd3a9a7e6fbc190df"
        app.dekorate.io/vcs-url: "https://github.com/huqianghui/kubernetes.git"
      labels:
        app.kubernetes.io/name: "spring-config-server"
        app.kubernetes.io/version: "1.0.3-SNAPSHOT"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "huqianghui/spring-config-server:1.0.3-SNAPSHOT"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/info"
            port: 8888
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: "spring-config-server"
        ports:
        - containerPort: 8888
          name: "http"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/health"
            port: 8888
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccount: "spring-config-server"
