# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: self-hosted Maven build & push to ACR

on: [push]

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }} # default: index.docker.io
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASS1 }} 
    - run: echo "🎉 Login into azure container registry..." 
    - name: Build with Maven
      run: cd /Users/huqianghui/Downloads/springcloud2k8s/spring-boot-v1-kubernetes-demo && mvn clean install -Dmaven.test.skip=true --file ./pom.xml
